"""
Publish the project to Hugging Face Hub:
  1. Dataset repo with train/val/test JSONL + dataset card
  2. (Optional) Model card repo documenting the fine-tune, linking to Replicate

Replicate hosts the fine-tuned weights, so the "model" repo here is a
documentation/model-card repo — standard practice when weights live elsewhere.

Prerequisites:
    pip install huggingface_hub
    export HF_TOKEN=hf_xxx   (write-scoped token from hf.co/settings/tokens)

Usage:
    python deploy/push_to_hf.py --username your-hf-username
"""

import argparse
import os
from pathlib import Path

from huggingface_hub import HfApi

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DATASET_CARD = """---
license: mit
task_categories:
- summarization
language:
- en
tags:
- medical
- clinical-notes
- synthetic
size_categories:
- n<1K
---

# Synthetic Clinical Note Summarization Dataset

600 fully synthetic SOAP-style clinical notes paired with structured summaries
(DIAGNOSIS / KEY FINDINGS / MEDICATIONS / ACTION ITEMS / FOLLOW-UP), formatted
for Llama 2 fine-tuning on Replicate (`{"prompt": ..., "completion": ...}`).

- 10 condition templates (diabetes, hypertension, pneumonia, depression, asthma,
  GERD, UTI, osteoarthritis, hypothyroidism, migraine)
- Randomized demographics, vitals, labs, medications, and plans
- No real patient data. Generated by `data/generate_dataset.py` in the project repo.

**Splits:** train 510 / val 45 / test 45
"""

MODEL_CARD = """---
license: llama2
base_model: meta-llama/Llama-2-7b
tags:
- summarization
- medical
- replicate
- lora
---

# Llama 2 7B — Clinical Note Summarizer

Llama 2 7B fine-tuned (LoRA, via Replicate managed training) to convert
free-text clinical notes into structured summaries with fixed sections:
DIAGNOSIS, KEY FINDINGS, MEDICATIONS, ACTION ITEMS, FOLLOW-UP.

Weights are hosted on Replicate; run with:

```python
import replicate
output = replicate.run("<username>/llama2-med-summarizer:<version>",
                       input={"prompt": "...", "max_new_tokens": 300, "temperature": 0.2})
```

## Evaluation (held-out test set, base vs fine-tuned)

See `results/eval_report.json` in the project repo for the exact numbers of
your run. Metrics: ROUGE-1/2/L, BLEU, structure compliance (5-section format
adherence), and number fidelity (fraction of numbers in the summary present in
the source note — a hallucination check for invented dosages/vitals).

## Intended use & limitations

Educational/portfolio project trained on synthetic data. Not validated for
clinical use; do not use with real patient data or for medical decisions.
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--username", required=True)
    parser.add_argument("--dataset-name", default="synthetic-clinical-note-summaries")
    parser.add_argument("--model-name", default="llama2-7b-med-summarizer")
    parser.add_argument("--skip-model-card", action="store_true")
    args = parser.parse_args()

    token = os.getenv("HF_TOKEN")
    if not token:
        raise SystemExit("Set HF_TOKEN environment variable first.")
    api = HfApi(token=token)

    # --- Dataset repo ---
    ds_repo = f"{args.username}/{args.dataset_name}"
    api.create_repo(ds_repo, repo_type="dataset", exist_ok=True)
    (PROJECT_ROOT / "data" / "README.md").write_text(DATASET_CARD)
    for fname in ["README.md", "train.jsonl", "val.jsonl", "test.jsonl"]:
        api.upload_file(
            path_or_fileobj=PROJECT_ROOT / "data" / fname,
            path_in_repo=fname,
            repo_id=ds_repo,
            repo_type="dataset",
        )
    print(f"Dataset pushed -> https://huggingface.co/datasets/{ds_repo}")

    # --- Model card repo ---
    if not args.skip_model_card:
        model_repo = f"{args.username}/{args.model_name}"
        api.create_repo(model_repo, exist_ok=True)
        card_path = PROJECT_ROOT / "deploy" / "MODEL_CARD.md"
        card_path.write_text(MODEL_CARD)
        api.upload_file(
            path_or_fileobj=card_path,
            path_in_repo="README.md",
            repo_id=model_repo,
        )
        eval_report = PROJECT_ROOT / "results" / "eval_report.json"
        if eval_report.exists():
            api.upload_file(
                path_or_fileobj=eval_report,
                path_in_repo="eval_report.json",
                repo_id=model_repo,
            )
        print(f"Model card pushed -> https://huggingface.co/{model_repo}")


if __name__ == "__main__":
    main()
